services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8000"

  car-service:
    build: ./car-service
    container_name: car-service
    ports:
      - "8001:8001"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.car.rule=PathPrefix(`/api/cars`)"
      - "traefik.http.services.car.loadbalancer.server.port=8001"

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8002:8002"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - consul
      - rabbitmq
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booking.rule=PathPrefix(`/api/bookings`)"
      - "traefik.http.services.booking.loadbalancer.server.port=8002"

  celery-worker:
    build: ./booking-service
    container_name: celery-worker
    command: celery -A booking_project worker --loglevel=info --pool=solo
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq
      - booking-service
    networks:
      - app-network

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./dynamic.yml:/etc/traefik/dynamic.yml"
    depends_on:
      - auth-service
      - car-service
      - booking-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge